### ISSUE TITLE
Can't understand where keylogger results are saved or how to get them.

### ISSUE THREAD

**Issue by And329** [joaoviictorti/shadow-rs#1]
I tried to examine the code but wasn't able to figure it out :(

**Comment by joaoviictorti** [comment]
Hi @And329, I'm finalizing this implementation of the keylogger. Currently, it only sends the logs to the kernel which you can see using DebugView or even Windbg. 

It works on Windows 10, but on Windows 11 the implementation is different. The project is still in development and various features and updates will be coming to the code. 😁

**Comment by And329** [comment]
yh, copilot helped me to figure it out))) I really love what you are doing tho) KEEP IT UP!!!!
